name: Generate and Deploy Reference Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - run: mvn -f code/sdk dokka:dokka

      - uses: actions/upload-pages-artifact@v3
        with:
          name: dokka-artifact
          path: './code/sdk/target/dokka'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4