/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Phone
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * Object to hold information for a contact the supplier can reach in the event of any issues with the provided payment.
 * @param email The email address of the VCC contact.
 * @param phone
 */
data class AdditionalHandlingCardContact(
    // The email address of the VCC contact.
    @JsonProperty("email")
    @field:Valid
    val email: kotlin.String? = null,
    @JsonProperty("phone")
    @field:Valid
    val phone: Phone? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var email: kotlin.String? = null,
        private var phone: Phone? = null
    ) {
        fun email(email: kotlin.String?) = apply { this.email = email }

        fun phone(phone: Phone?) = apply { this.phone = phone }

        fun build(): AdditionalHandlingCardContact {
            val instance =
                AdditionalHandlingCardContact(
                    email = email,
                    phone = phone
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: AdditionalHandlingCardContact) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            email = email,
            phone = phone
        )
}
