/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * An individual attribute reference.
 * @param id The attribute definition ID for this attribute.
 * @param name Attribute name.
 * @param hasValue Indicates whether an attribute will have an associated numeric value.
 */
data class AttributeReference(
    // The attribute definition ID for this attribute.
    @JsonProperty("id")
    @field:Valid
    val id: kotlin.String? = null,
    // Attribute name.
    @JsonProperty("name")
    @field:Valid
    val name: kotlin.String? = null,
    // Indicates whether an attribute will have an associated numeric value.
    @JsonProperty("has_value")
    @field:Valid
    val hasValue: kotlin.Boolean? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var id: kotlin.String? = null,
        private var name: kotlin.String? = null,
        private var hasValue: kotlin.Boolean? = null
    ) {
        fun id(id: kotlin.String?) = apply { this.id = id }

        fun name(name: kotlin.String?) = apply { this.name = name }

        fun hasValue(hasValue: kotlin.Boolean?) = apply { this.hasValue = hasValue }

        fun build(): AttributeReference {
            val instance =
                AttributeReference(
                    id = id,
                    name = name,
                    hasValue = hasValue
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: AttributeReference) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            id = id,
            name = name,
            hasValue = hasValue
        )
}
