/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Link1
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.NotNull

/**
 *
 * @param view
 * @param render
 * @param click
 */
data class Beacons(
    @JsonProperty("view")
    @field:NotNull
    @field:Valid
    val view: Link1,
    @JsonProperty("render")
    @field:NotNull
    @field:Valid
    val render: Link1,
    @JsonProperty("click")
    @field:NotNull
    @field:Valid
    val click: Link1
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var view: Link1? = null,
        private var render: Link1? = null,
        private var click: Link1? = null
    ) {
        fun view(view: Link1) = apply { this.view = view }

        fun render(render: Link1) = apply { this.render = render }

        fun click(click: Link1) = apply { this.click = click }

        fun build(): Beacons {
            val instance =
                Beacons(
                    view = view!!,
                    render = render!!,
                    click = click!!
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Beacons) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            view = view!!,
            render = render!!,
            click = click!!
        )
}
