/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.CampaignCuratedContent
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 *
 * @param campaignId Unique identifier for the campaign
 * @param blockoutDates Boolean value indicating if promotions with blockout dates are included in this campaign.
 * @param bookableEnd The last date that bookings can be made on in this campaign, in ISO 8601 format (YYYY-MM-DD).
 * @param bookableStart The first date that bookings can be made on in this campaign, in ISO 8601 format (YYYY-MM-DD).
 * @param curatedContent
 * @param lifetime The type of lifetime of this campaign.
 * @param maxDiscount The maximum discount amount that is included in a campaign.
 * @param minDiscount The minimum discount amount that is included in a campaign.
 * @param name The name of the campaign.
 * @param propertyCount The number of properties participating in this campaign.
 * @param stayEnd The last date that check-ins can be set to in this campaign in ISO 8601 format (YYYY-MM-DD).
 * @param stayStart The first date that check-ins can be set to in this campaign in ISO 8601 format (YYYY-MM-DD).
 */
data class Campaign(
    // Unique identifier for the campaign
    @JsonProperty("campaign_id")
    @field:Valid
    val campaignId: kotlin.String? = null,
    // Boolean value indicating if promotions with blockout dates are included in this campaign.
    @JsonProperty("blockout_dates")
    @field:Valid
    val blockoutDates: kotlin.Boolean? = null,
    // The last date that bookings can be made on in this campaign, in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("bookable_end")
    @field:Valid
    val bookableEnd: kotlin.String? = null,
    // The first date that bookings can be made on in this campaign, in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("bookable_start")
    @field:Valid
    val bookableStart: kotlin.String? = null,
    @JsonProperty("curated_content")
    @field:Valid
    val curatedContent: CampaignCuratedContent? = null,
    // The type of lifetime of this campaign.
    @JsonProperty("lifetime")
    @field:Valid
    val lifetime: kotlin.String? = null,
    // The maximum discount amount that is included in a campaign.
    @JsonProperty("max_discount")
    @field:Valid
    val maxDiscount: kotlin.String? = null,
    // The minimum discount amount that is included in a campaign.
    @JsonProperty("min_discount")
    @field:Valid
    val minDiscount: kotlin.String? = null,
    // The name of the campaign.
    @JsonProperty("name")
    @field:Valid
    val name: kotlin.String? = null,
    // The number of properties participating in this campaign.
    @JsonProperty("property_count")
    @field:Valid
    val propertyCount: kotlin.String? = null,
    // The last date that check-ins can be set to in this campaign in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("stay_end")
    @field:Valid
    val stayEnd: kotlin.String? = null,
    // The first date that check-ins can be set to in this campaign in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("stay_start")
    @field:Valid
    val stayStart: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var campaignId: kotlin.String? = null,
        private var blockoutDates: kotlin.Boolean? = null,
        private var bookableEnd: kotlin.String? = null,
        private var bookableStart: kotlin.String? = null,
        private var curatedContent: CampaignCuratedContent? = null,
        private var lifetime: kotlin.String? = null,
        private var maxDiscount: kotlin.String? = null,
        private var minDiscount: kotlin.String? = null,
        private var name: kotlin.String? = null,
        private var propertyCount: kotlin.String? = null,
        private var stayEnd: kotlin.String? = null,
        private var stayStart: kotlin.String? = null
    ) {
        fun campaignId(campaignId: kotlin.String?) = apply { this.campaignId = campaignId }

        fun blockoutDates(blockoutDates: kotlin.Boolean?) = apply { this.blockoutDates = blockoutDates }

        fun bookableEnd(bookableEnd: kotlin.String?) = apply { this.bookableEnd = bookableEnd }

        fun bookableStart(bookableStart: kotlin.String?) = apply { this.bookableStart = bookableStart }

        fun curatedContent(curatedContent: CampaignCuratedContent?) = apply { this.curatedContent = curatedContent }

        fun lifetime(lifetime: kotlin.String?) = apply { this.lifetime = lifetime }

        fun maxDiscount(maxDiscount: kotlin.String?) = apply { this.maxDiscount = maxDiscount }

        fun minDiscount(minDiscount: kotlin.String?) = apply { this.minDiscount = minDiscount }

        fun name(name: kotlin.String?) = apply { this.name = name }

        fun propertyCount(propertyCount: kotlin.String?) = apply { this.propertyCount = propertyCount }

        fun stayEnd(stayEnd: kotlin.String?) = apply { this.stayEnd = stayEnd }

        fun stayStart(stayStart: kotlin.String?) = apply { this.stayStart = stayStart }

        fun build(): Campaign {
            val instance =
                Campaign(
                    campaignId = campaignId,
                    blockoutDates = blockoutDates,
                    bookableEnd = bookableEnd,
                    bookableStart = bookableStart,
                    curatedContent = curatedContent,
                    lifetime = lifetime,
                    maxDiscount = maxDiscount,
                    minDiscount = minDiscount,
                    name = name,
                    propertyCount = propertyCount,
                    stayEnd = stayEnd,
                    stayStart = stayStart
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Campaign) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            campaignId = campaignId,
            blockoutDates = blockoutDates,
            bookableEnd = bookableEnd,
            bookableStart = bookableStart,
            curatedContent = curatedContent,
            lifetime = lifetime,
            maxDiscount = maxDiscount,
            minDiscount = minDiscount,
            name = name,
            propertyCount = propertyCount,
            stayEnd = stayEnd,
            stayStart = stayStart
        )
}
