/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.MarketRegionContent
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * Curated content object containing map of campaign regions containing various curated content objects
 * @param anz
 * @param asia
 * @param ca
 * @param emea
 * @param latam
 * @param us
 */
data class CampaignCuratedContent(
    @JsonProperty("anz")
    @field:Valid
    val anz: MarketRegionContent? = null,
    @JsonProperty("asia")
    @field:Valid
    val asia: MarketRegionContent? = null,
    @JsonProperty("ca")
    @field:Valid
    val ca: MarketRegionContent? = null,
    @JsonProperty("emea")
    @field:Valid
    val emea: MarketRegionContent? = null,
    @JsonProperty("latam")
    @field:Valid
    val latam: MarketRegionContent? = null,
    @JsonProperty("us")
    @field:Valid
    val us: MarketRegionContent? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var anz: MarketRegionContent? = null,
        private var asia: MarketRegionContent? = null,
        private var ca: MarketRegionContent? = null,
        private var emea: MarketRegionContent? = null,
        private var latam: MarketRegionContent? = null,
        private var us: MarketRegionContent? = null
    ) {
        fun anz(anz: MarketRegionContent?) = apply { this.anz = anz }

        fun asia(asia: MarketRegionContent?) = apply { this.asia = asia }

        fun ca(ca: MarketRegionContent?) = apply { this.ca = ca }

        fun emea(emea: MarketRegionContent?) = apply { this.emea = emea }

        fun latam(latam: MarketRegionContent?) = apply { this.latam = latam }

        fun us(us: MarketRegionContent?) = apply { this.us = us }

        fun build(): CampaignCuratedContent {
            val instance =
                CampaignCuratedContent(
                    anz = anz,
                    asia = asia,
                    ca = ca,
                    emea = emea,
                    latam = latam,
                    us = us
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: CampaignCuratedContent) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            anz = anz,
            asia = asia,
            ca = ca,
            emea = emea,
            latam = latam,
            us = us
        )
}
