/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation
import javax.validation.constraints.Max
import javax.validation.constraints.Min

/**
 *
 * @param latitude
 * @param longitude
 */
data class Coordinates1(
    @JsonProperty("latitude")
    @field:Min(-90)
    @field:Max(90)
    @field:Valid
    val latitude: java.math.BigDecimal? = null,
    @JsonProperty("longitude")
    @field:Min(-180)
    @field:Max(180)
    @field:Valid
    val longitude: java.math.BigDecimal? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var latitude: java.math.BigDecimal? = null,
        private var longitude: java.math.BigDecimal? = null
    ) {
        fun latitude(latitude: java.math.BigDecimal?) = apply { this.latitude = latitude }

        fun longitude(longitude: java.math.BigDecimal?) = apply { this.longitude = longitude }

        fun build(): Coordinates1 {
            val instance =
                Coordinates1(
                    latitude = latitude,
                    longitude = longitude
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Coordinates1) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            latitude = latitude,
            longitude = longitude
        )
}
