/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Address1
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * Additional sensitive (PII) data about a traveler that should only be submitted in cases where it is necessary to clarify the identity of the traveler.
 * @param middleName Middle name of room guest. Max 60 characters. Special characters (\"<\", \">\", \"(\", \")\", and \"&\") entered in this field will be re-encoded.
 * @param dateOfBirth The date of birth of room guest, in ISO 8601 format (YYYY-MM-DD).
 * @param address
 */
data class CreateItineraryRequestRoomSensitiveTravelerDetails(
    // Middle name of room guest. Max 60 characters. Special characters (\"<\", \">\", \"(\", \")\", and \"&\") entered in this field will be re-encoded.
    @JsonProperty("middle_name")
    @field:Valid
    val middleName: kotlin.String? = null,
    // The date of birth of room guest, in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("date_of_birth")
    @field:Valid
    val dateOfBirth: kotlin.String? = null,
    @JsonProperty("address")
    @field:Valid
    val address: Address1? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var middleName: kotlin.String? = null,
        private var dateOfBirth: kotlin.String? = null,
        private var address: Address1? = null
    ) {
        fun middleName(middleName: kotlin.String?) = apply { this.middleName = middleName }

        fun dateOfBirth(dateOfBirth: kotlin.String?) = apply { this.dateOfBirth = dateOfBirth }

        fun address(address: Address1?) = apply { this.address = address }

        fun build(): CreateItineraryRequestRoomSensitiveTravelerDetails {
            val instance =
                CreateItineraryRequestRoomSensitiveTravelerDetails(
                    middleName = middleName,
                    dateOfBirth = dateOfBirth,
                    address = address
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: CreateItineraryRequestRoomSensitiveTravelerDetails) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            middleName = middleName,
            dateOfBirth = dateOfBirth,
            address = address
        )
}
