/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Address1
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * To be included if invoicing is requested.
 * @param companyName The traveler's company name to appear on the invoice.
 * @param companyAddress
 * @param pointOfSaleDisplay Provide this when a specific site or branding should be used on the invoice instead of partner name.
 * @param email Email address to send invoices
 */
data class CreateItineraryRequestInvoicing(
    // The traveler's company name to appear on the invoice.
    @JsonProperty("company_name")
    @field:Valid
    val companyName: kotlin.String? = null,
    @JsonProperty("company_address")
    @field:Valid
    val companyAddress: Address1? = null,
    // Provide this when a specific site or branding should be used on the invoice instead of partner name.
    @JsonProperty("point_of_sale_display")
    @field:Valid
    val pointOfSaleDisplay: kotlin.String? = null,
    // Email address to send invoices
    @JsonProperty("email")
    @field:Valid
    val email: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var companyName: kotlin.String? = null,
        private var companyAddress: Address1? = null,
        private var pointOfSaleDisplay: kotlin.String? = null,
        private var email: kotlin.String? = null
    ) {
        fun companyName(companyName: kotlin.String?) = apply { this.companyName = companyName }

        fun companyAddress(companyAddress: Address1?) = apply { this.companyAddress = companyAddress }

        fun pointOfSaleDisplay(pointOfSaleDisplay: kotlin.String?) = apply { this.pointOfSaleDisplay = pointOfSaleDisplay }

        fun email(email: kotlin.String?) = apply { this.email = email }

        fun build(): CreateItineraryRequestInvoicing {
            val instance =
                CreateItineraryRequestInvoicing(
                    companyName = companyName,
                    companyAddress = companyAddress,
                    pointOfSaleDisplay = pointOfSaleDisplay,
                    email = email
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: CreateItineraryRequestInvoicing) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            companyName = companyName,
            companyAddress = companyAddress,
            pointOfSaleDisplay = pointOfSaleDisplay,
            email = email
        )
}
