/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Image1
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * The headline, description, and image to be rendered for the sponsored listing.
 * @param headline The headline of the sponsored listing.
 * @param description The description of the sponsored listing.
 * @param image
 */
data class Creative(
    // The headline of the sponsored listing.
    @JsonProperty("headline")
    @field:Valid
    val headline: kotlin.String? = null,
    // The description of the sponsored listing.
    @JsonProperty("description")
    @field:Valid
    val description: kotlin.String? = null,
    @JsonProperty("image")
    @field:Valid
    val image: Image1? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var headline: kotlin.String? = null,
        private var description: kotlin.String? = null,
        private var image: Image1? = null
    ) {
        fun headline(headline: kotlin.String?) = apply { this.headline = headline }

        fun description(description: kotlin.String?) = apply { this.description = description }

        fun image(image: Image1?) = apply { this.image = image }

        fun build(): Creative {
            val instance =
                Creative(
                    headline = headline,
                    description = description,
                    image = image
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Creative) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            headline = headline,
            description = description,
            image = image
        )
}
