/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * An image object containing the link to the image and tags for the image.
 * @param image A link to the image.
 * @param tags Tags for the image.
 */
data class Image2(
    // A link to the image.
    @JsonProperty("image")
    @field:Valid
    val image: kotlin.String? = null,
    // Tags for the image.
    @JsonProperty("tags")
    @field:Valid
    val tags: kotlin.collections.List<kotlin.String>? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var image: kotlin.String? = null,
        private var tags: kotlin.collections.List<kotlin.String>? = null
    ) {
        fun image(image: kotlin.String?) = apply { this.image = image }

        fun tags(tags: kotlin.collections.List<kotlin.String>?) = apply { this.tags = tags }

        fun build(): Image2 {
            val instance =
                Image2(
                    image = image,
                    tags = tags
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Image2) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            image = image,
            tags = tags
        )
}
