/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Copy
import com.expediagroup.sdk.rapid.models.Image2
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 *
 * @param copy An array of copy objects that should be used for this campaign and region.
 * @param destinations An array of places a campaign is limited to having promotions in.
 * @param images An array of images associated with this campaign.
 * @param themes An array of themes associated with this campaign.
 */
data class MarketRegionContent(
    // An array of copy objects that should be used for this campaign and region.
    @JsonProperty("copy")
    @field:Valid
    val copy: kotlin.collections.List<Copy>? = null,
    // An array of places a campaign is limited to having promotions in.
    @JsonProperty("destinations")
    @field:Valid
    val destinations: kotlin.collections.List<kotlin.String>? = null,
    // An array of images associated with this campaign.
    @JsonProperty("images")
    @field:Valid
    val images: kotlin.collections.List<Image2>? = null,
    // An array of themes associated with this campaign.
    @JsonProperty("themes")
    @field:Valid
    val themes: kotlin.collections.List<kotlin.String>? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var copy: kotlin.collections.List<Copy>? = null,
        private var destinations: kotlin.collections.List<kotlin.String>? = null,
        private var images: kotlin.collections.List<Image2>? = null,
        private var themes: kotlin.collections.List<kotlin.String>? = null
    ) {
        fun copy(copy: kotlin.collections.List<Copy>?) = apply { this.copy = copy }

        fun destinations(destinations: kotlin.collections.List<kotlin.String>?) = apply { this.destinations = destinations }

        fun images(images: kotlin.collections.List<Image2>?) = apply { this.images = images }

        fun themes(themes: kotlin.collections.List<kotlin.String>?) = apply { this.themes = themes }

        fun build(): MarketRegionContent {
            val instance =
                MarketRegionContent(
                    copy = copy,
                    destinations = destinations,
                    images = images,
                    themes = themes
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: MarketRegionContent) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            copy = copy,
            destinations = destinations,
            images = images,
            themes = themes
        )
}
