/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.Charge
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * An object representing a more granular view and key components contributing to Marketing Fee estimates, in line with contracted commercial terms between Expedia and partner. * `base` - Potential earnings derived from standard or flat commission rates. * `overrides` - Potential earnings derived from additional variable commission rates, typically subject to   achievement of specific revenue targets. * `incentives` - Potential earnings derived from additional incentives, applicable for a limited time period. * `other` - Potential earnings derived from a category not yet covered by the above components.
 * @param base
 * @param overrides
 * @param incentives
 * @param other
 */
data class MarketingFeeDetails(
    @JsonProperty("base")
    @field:Valid
    val base: Charge? = null,
    @JsonProperty("overrides")
    @field:Valid
    val overrides: Charge? = null,
    @JsonProperty("incentives")
    @field:Valid
    val incentives: Charge? = null,
    @JsonProperty("other")
    @field:Valid
    val other: Charge? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var base: Charge? = null,
        private var overrides: Charge? = null,
        private var incentives: Charge? = null,
        private var other: Charge? = null
    ) {
        fun base(base: Charge?) = apply { this.base = base }

        fun overrides(overrides: Charge?) = apply { this.overrides = overrides }

        fun incentives(incentives: Charge?) = apply { this.incentives = incentives }

        fun other(other: Charge?) = apply { this.other = other }

        fun build(): MarketingFeeDetails {
            val instance =
                MarketingFeeDetails(
                    base = base,
                    overrides = overrides,
                    incentives = incentives,
                    other = other
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: MarketingFeeDetails) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            base = base,
            overrides = overrides,
            incentives = incentives,
            other = other
        )
}
