/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * Maximum occupancy counts.
 * @param total Total maximum occupancy allowed.
 * @param children Maximum number of children allowed.
 * @param adults Maximum number of adults allowed.
 */
data class MaxAllowed(
    // Total maximum occupancy allowed.
    @JsonProperty("total")
    @field:Valid
    val total: java.math.BigDecimal? = null,
    // Maximum number of children allowed.
    @JsonProperty("children")
    @field:Valid
    val children: java.math.BigDecimal? = null,
    // Maximum number of adults allowed.
    @JsonProperty("adults")
    @field:Valid
    val adults: java.math.BigDecimal? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var total: java.math.BigDecimal? = null,
        private var children: java.math.BigDecimal? = null,
        private var adults: java.math.BigDecimal? = null
    ) {
        fun total(total: java.math.BigDecimal?) = apply { this.total = total }

        fun children(children: java.math.BigDecimal?) = apply { this.children = children }

        fun adults(adults: java.math.BigDecimal?) = apply { this.adults = adults }

        fun build(): MaxAllowed {
            val instance =
                MaxAllowed(
                    total = total,
                    children = children,
                    adults = adults
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: MaxAllowed) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            total = total,
            children = children,
            adults = adults
        )
}
