/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.AffiliateCollect
import com.expediagroup.sdk.rapid.models.CreditCard
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * The payment option response.
 * @param affiliateCollect
 * @param creditCard
 */
data class PaymentOption(
    @JsonProperty("affiliate_collect")
    @field:Valid
    val affiliateCollect: AffiliateCollect? = null,
    @JsonProperty("credit_card")
    @field:Valid
    val creditCard: CreditCard? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var affiliateCollect: AffiliateCollect? = null,
        private var creditCard: CreditCard? = null
    ) {
        fun affiliateCollect(affiliateCollect: AffiliateCollect?) = apply { this.affiliateCollect = affiliateCollect }

        fun creditCard(creditCard: CreditCard?) = apply { this.creditCard = creditCard }

        fun build(): PaymentOption {
            val instance =
                PaymentOption(
                    affiliateCollect = affiliateCollect,
                    creditCard = creditCard
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: PaymentOption) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            affiliateCollect = affiliateCollect,
            creditCard = creditCard
        )
}
