/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 * A map of ranks with 1 being the best and descending from there.
 * @param destination Rank of the destination associated with the promotion.
 * @param promotion Rank of the promotion itself.
 * @param `property` Rank of the property associated with the promotion.
 */
data class PromotionRank(
    // Rank of the destination associated with the promotion.
    @JsonProperty("destination")
    @field:Valid
    val destination: kotlin.String? = null,
    // Rank of the promotion itself.
    @JsonProperty("promotion")
    @field:Valid
    val promotion: kotlin.String? = null,
    // Rank of the property associated with the promotion.
    @JsonProperty("property")
    @field:Valid
    val `property`: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var destination: kotlin.String? = null,
        private var promotion: kotlin.String? = null,
        private var `property`: kotlin.String? = null
    ) {
        fun destination(destination: kotlin.String?) = apply { this.destination = destination }

        fun promotion(promotion: kotlin.String?) = apply { this.promotion = promotion }

        fun `property`(`property`: kotlin.String?) = apply { this.`property` = `property` }

        fun build(): PromotionRank {
            val instance =
                PromotionRank(
                    destination = destination,
                    promotion = promotion,
                    `property` = `property`
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: PromotionRank) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            destination = destination,
            promotion = promotion,
            `property` = `property`
        )
}
