/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.expediagroup.sdk.core.model.exception.client.PropertyConstraintViolationException
import com.expediagroup.sdk.rapid.models.BlockoutDate
import com.expediagroup.sdk.rapid.models.PromotionLinks
import com.expediagroup.sdk.rapid.models.PromotionRank
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
import javax.validation.Valid
import javax.validation.Validation

/**
 *
 * @param promotionId Unique identifier for the promotion
 * @param blockoutDates An array of stay date ranges within this check-in / check-out range that are not eligible for this promotion. The stay dates are determined by the would be check-in of that night. With a check-in date of 2023-09-01, and a check-out date of 2023-09-06, this would be a 5 night stay. A `blockout_dates` with start: '2023-09-02' and end: 2023-09-03 would mean 2 of the nights are not eligible. The 1st night is eligible, the 2nd and 3rd nights are not eligible, and the 4th and 5th nights are eligible.
 * @param bookableEnd The last date that bookings can be made on in this promotion, in ISO 8601 format (YYYY-MM-DD).
 * @param bookableStart The first date that bookings can be made on in this promotion, in ISO 8601 format (YYYY-MM-DD).
 * @param campaignId The campaign id this promotion is associated with.
 * @param categoryId The category id of the property.
 * @param chainId The chain id for the property.
 * @param description The description of the promotion.
 * @param discountPercentage The percent off of the cost of the property when using this promotion. This will only be returned for percentage based promotions
 * @param guestRating The overall rating for the property, averaged from all guest reviews. Returns a value between 1.0 and 5.0.
 * @param lifetime The type of lifetime of this promotion.
 * @param links
 * @param marketRegion The market region for the promotion.
 * @param membersOnly Boolean value indicating if a promotion is for members only.
 * @param minAdvancePurchaseDays The least number of days before check-in a stay must be booked to use this promotion.
 * @param minStay The least number of days that must be booked to use this promotion.
 * @param mobileOnly Boolean value indicating if a promotion is for mobile only.
 * @param productLines The list of product lines.
 * @param propertyId Unique Expedia property ID.
 * @param rank
 * @param regionId The region id for the property.
 * @param starRating The rating assigned to this property. Returns a value between 0.0 and 5.0. A value of 0.0 or a blank value indicates no rating is available.
 * @param stayEnd The last date that check-ins can be set to in this promotion in ISO 8601 format (YYYY-MM-DD).
 * @param stayStart The first date that check-ins can be set to in this promotion in ISO 8601 format (YYYY-MM-DD).
 * @param supplySource The supply source of the property.
 */
data class Promotion(
    // Unique identifier for the promotion
    @JsonProperty("promotion_id")
    @field:Valid
    val promotionId: kotlin.String? = null,
    // An array of stay date ranges within this check-in / check-out range that are not eligible for this promotion. The stay dates are determined by the would be check-in of that night. With a check-in date of 2023-09-01, and a check-out date of 2023-09-06, this would be a 5 night stay. A `blockout_dates` with start: '2023-09-02' and end: 2023-09-03 would mean 2 of the nights are not eligible. The 1st night is eligible, the 2nd and 3rd nights are not eligible, and the 4th and 5th nights are eligible.
    @JsonProperty("blockout_dates")
    @field:Valid
    val blockoutDates: kotlin.collections.List<BlockoutDate>? = null,
    // The last date that bookings can be made on in this promotion, in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("bookable_end")
    @field:Valid
    val bookableEnd: kotlin.String? = null,
    // The first date that bookings can be made on in this promotion, in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("bookable_start")
    @field:Valid
    val bookableStart: kotlin.String? = null,
    // The campaign id this promotion is associated with.
    @JsonProperty("campaign_id")
    @field:Valid
    val campaignId: kotlin.String? = null,
    // The category id of the property.
    @JsonProperty("category_id")
    @field:Valid
    val categoryId: kotlin.String? = null,
    // The chain id for the property.
    @JsonProperty("chain_id")
    @field:Valid
    val chainId: kotlin.String? = null,
    // The description of the promotion.
    @JsonProperty("description")
    @field:Valid
    val description: kotlin.String? = null,
    // The percent off of the cost of the property when using this promotion. This will only be returned for percentage based promotions
    @JsonProperty("discount_percentage")
    @field:Valid
    val discountPercentage: kotlin.String? = null,
    // The overall rating for the property, averaged from all guest reviews. Returns a value between 1.0 and 5.0.
    @JsonProperty("guest_rating")
    @field:Valid
    val guestRating: kotlin.String? = null,
    // The type of lifetime of this promotion.
    @JsonProperty("lifetime")
    @field:Valid
    val lifetime: kotlin.String? = null,
    @JsonProperty("links")
    @field:Valid
    val links: PromotionLinks? = null,
    // The market region for the promotion.
    @JsonProperty("market_region")
    @field:Valid
    val marketRegion: kotlin.String? = null,
    // Boolean value indicating if a promotion is for members only.
    @JsonProperty("members_only")
    @field:Valid
    val membersOnly: kotlin.String? = null,
    // The least number of days before check-in a stay must be booked to use this promotion.
    @JsonProperty("min_advance_purchase_days")
    @field:Valid
    val minAdvancePurchaseDays: kotlin.String? = null,
    // The least number of days that must be booked to use this promotion.
    @JsonProperty("min_stay")
    @field:Valid
    val minStay: kotlin.String? = null,
    // Boolean value indicating if a promotion is for mobile only.
    @JsonProperty("mobile_only")
    @field:Valid
    val mobileOnly: kotlin.String? = null,
    // The list of product lines.
    @JsonProperty("product_lines")
    @field:Valid
    val productLines: kotlin.collections.List<kotlin.String>? = null,
    // Unique Expedia property ID.
    @JsonProperty("property_id")
    @field:Valid
    val propertyId: kotlin.String? = null,
    @JsonProperty("rank")
    @field:Valid
    val rank: PromotionRank? = null,
    // The region id for the property.
    @JsonProperty("region_id")
    @field:Valid
    val regionId: kotlin.String? = null,
    // The rating assigned to this property. Returns a value between 0.0 and 5.0. A value of 0.0 or a blank value indicates no rating is available.
    @JsonProperty("star_rating")
    @field:Valid
    val starRating: kotlin.String? = null,
    // The last date that check-ins can be set to in this promotion in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("stay_end")
    @field:Valid
    val stayEnd: kotlin.String? = null,
    // The first date that check-ins can be set to in this promotion in ISO 8601 format (YYYY-MM-DD).
    @JsonProperty("stay_start")
    @field:Valid
    val stayStart: kotlin.String? = null,
    // The supply source of the property.
    @JsonProperty("supply_source")
    @field:Valid
    val supplySource: kotlin.String? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var promotionId: kotlin.String? = null,
        private var blockoutDates: kotlin.collections.List<BlockoutDate>? = null,
        private var bookableEnd: kotlin.String? = null,
        private var bookableStart: kotlin.String? = null,
        private var campaignId: kotlin.String? = null,
        private var categoryId: kotlin.String? = null,
        private var chainId: kotlin.String? = null,
        private var description: kotlin.String? = null,
        private var discountPercentage: kotlin.String? = null,
        private var guestRating: kotlin.String? = null,
        private var lifetime: kotlin.String? = null,
        private var links: PromotionLinks? = null,
        private var marketRegion: kotlin.String? = null,
        private var membersOnly: kotlin.String? = null,
        private var minAdvancePurchaseDays: kotlin.String? = null,
        private var minStay: kotlin.String? = null,
        private var mobileOnly: kotlin.String? = null,
        private var productLines: kotlin.collections.List<kotlin.String>? = null,
        private var propertyId: kotlin.String? = null,
        private var rank: PromotionRank? = null,
        private var regionId: kotlin.String? = null,
        private var starRating: kotlin.String? = null,
        private var stayEnd: kotlin.String? = null,
        private var stayStart: kotlin.String? = null,
        private var supplySource: kotlin.String? = null
    ) {
        fun promotionId(promotionId: kotlin.String?) = apply { this.promotionId = promotionId }

        fun blockoutDates(blockoutDates: kotlin.collections.List<BlockoutDate>?) = apply { this.blockoutDates = blockoutDates }

        fun bookableEnd(bookableEnd: kotlin.String?) = apply { this.bookableEnd = bookableEnd }

        fun bookableStart(bookableStart: kotlin.String?) = apply { this.bookableStart = bookableStart }

        fun campaignId(campaignId: kotlin.String?) = apply { this.campaignId = campaignId }

        fun categoryId(categoryId: kotlin.String?) = apply { this.categoryId = categoryId }

        fun chainId(chainId: kotlin.String?) = apply { this.chainId = chainId }

        fun description(description: kotlin.String?) = apply { this.description = description }

        fun discountPercentage(discountPercentage: kotlin.String?) = apply { this.discountPercentage = discountPercentage }

        fun guestRating(guestRating: kotlin.String?) = apply { this.guestRating = guestRating }

        fun lifetime(lifetime: kotlin.String?) = apply { this.lifetime = lifetime }

        fun links(links: PromotionLinks?) = apply { this.links = links }

        fun marketRegion(marketRegion: kotlin.String?) = apply { this.marketRegion = marketRegion }

        fun membersOnly(membersOnly: kotlin.String?) = apply { this.membersOnly = membersOnly }

        fun minAdvancePurchaseDays(minAdvancePurchaseDays: kotlin.String?) = apply { this.minAdvancePurchaseDays = minAdvancePurchaseDays }

        fun minStay(minStay: kotlin.String?) = apply { this.minStay = minStay }

        fun mobileOnly(mobileOnly: kotlin.String?) = apply { this.mobileOnly = mobileOnly }

        fun productLines(productLines: kotlin.collections.List<kotlin.String>?) = apply { this.productLines = productLines }

        fun propertyId(propertyId: kotlin.String?) = apply { this.propertyId = propertyId }

        fun rank(rank: PromotionRank?) = apply { this.rank = rank }

        fun regionId(regionId: kotlin.String?) = apply { this.regionId = regionId }

        fun starRating(starRating: kotlin.String?) = apply { this.starRating = starRating }

        fun stayEnd(stayEnd: kotlin.String?) = apply { this.stayEnd = stayEnd }

        fun stayStart(stayStart: kotlin.String?) = apply { this.stayStart = stayStart }

        fun supplySource(supplySource: kotlin.String?) = apply { this.supplySource = supplySource }

        fun build(): Promotion {
            val instance =
                Promotion(
                    promotionId = promotionId,
                    blockoutDates = blockoutDates,
                    bookableEnd = bookableEnd,
                    bookableStart = bookableStart,
                    campaignId = campaignId,
                    categoryId = categoryId,
                    chainId = chainId,
                    description = description,
                    discountPercentage = discountPercentage,
                    guestRating = guestRating,
                    lifetime = lifetime,
                    links = links,
                    marketRegion = marketRegion,
                    membersOnly = membersOnly,
                    minAdvancePurchaseDays = minAdvancePurchaseDays,
                    minStay = minStay,
                    mobileOnly = mobileOnly,
                    productLines = productLines,
                    propertyId = propertyId,
                    rank = rank,
                    regionId = regionId,
                    starRating = starRating,
                    stayEnd = stayEnd,
                    stayStart = stayStart,
                    supplySource = supplySource
                )

            validate(instance)

            return instance
        }

        private fun validate(instance: Promotion) {
            val validator =
                Validation
                    .byDefaultProvider()
                    .configure()
                    .messageInterpolator(ParameterMessageInterpolator())
                    .buildValidatorFactory()
                    .validator

            val violations = validator.validate(instance)

            if (violations.isNotEmpty()) {
                throw PropertyConstraintViolationException(
                    constraintViolations = violations.map { "${it.propertyPath}: ${it.message}" }
                )
            }
        }
    }

    fun toBuilder() =
        Builder(
            promotionId = promotionId,
            blockoutDates = blockoutDates,
            bookableEnd = bookableEnd,
            bookableStart = bookableStart,
            campaignId = campaignId,
            categoryId = categoryId,
            chainId = chainId,
            description = description,
            discountPercentage = discountPercentage,
            guestRating = guestRating,
            lifetime = lifetime,
            links = links,
            marketRegion = marketRegion,
            membersOnly = membersOnly,
            minAdvancePurchaseDays = minAdvancePurchaseDays,
            minStay = minStay,
            mobileOnly = mobileOnly,
            productLines = productLines,
            propertyId = propertyId,
            rank = rank,
            regionId = regionId,
            starRating = starRating,
            stayEnd = stayEnd,
            stayStart = stayStart,
            supplySource = supplySource
        )
}
