/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.rapid.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
* Indicates the status of the rate. * `available` - The rate is still available at or below the price returned in the shop response. * `available_no_change` - **Only in Hard Change flows** - The rate is available but matches the booked rate. * `price_changed` - The rate is no longer available at the previous price. Use the `additional_rates` link to   present updated rooms and rates for this property to travelers. * `sold_out` - The rate is no longer available at any price. Use the `additional_rates` link to   present updated rooms and rates for this property to travelers.
* Values: AVAILABLE,AVAILABLE_NO_CHANGE,PRICE_CHANGED,SOLD_OUT
*/
enum class StatusPriceCheck(val value: kotlin.String) {
    @JsonProperty("available")
    AVAILABLE("available"),

    @JsonProperty("available_no_change")
    AVAILABLE_NO_CHANGE("available_no_change"),

    @JsonProperty("price_changed")
    PRICE_CHANGED("price_changed"),

    @JsonProperty("sold_out")
    SOLD_OUT("sold_out")
}
