name: Generate and Publish SDK

on:
  workflow_dispatch:
    inputs:
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-java-sdk` repository.
          Defaults to the 'main' branch.
        type: string
        default: 'main'
      branch:
        description: |
          Branch to release the SDK from. Defaults to 'main'
        type: string
        default: 'main'

jobs:
  release-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Call SDK release workflow
        run: |
          gh workflow run ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-release-sdk.yaml --ref ${{ inputs.sdk_repo_ref }} --field branch=${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}