name: Generate and Publish SDK

on:
  workflow_dispatch:
    inputs:
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-java-sdk` repository.
          Defaults to the 'main' branch.
        type: string
        default: 'main'
      branch:
        description: |
          Branch to release the SDK from. Defaults to 'main'
        type: string
        default: 'main'

jobs:
  release-sdk:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-release-sdk.yaml@mohnoor94/SDK-1441
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}