name: Generate and Publish SDK

on:
  workflow_dispatch:
    inputs:
#      version:
#        description: |
#          SDK Version.
#          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
#        required: true
#        type: string
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-java-sdk` repository.
          Defaults to the 'main' branch.
        type: string
      branch:
        description: |
          Branch to release the SDK from. Defaults to 'main'
        type: string
        default: 'main'

jobs:
#  generate-and-publish-sources:
#    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@${{ inputs.sdk_repo_ref }}
#    secrets: inherit
#    with:
#      name: rapid
#      version: ${{ inputs.version }}
#      transformations: "-th -te /v3 --operationIdsToTags"
#      repository:  'ExpediaGroup/rapid-java-sdk'
#      sdk_repo_ref: ${{ inputs.sdk_repo_ref }}

  release-sdk:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-release-sdk.yaml@${{inputs.sdk_repo_ref}}
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}