name: Generate and Publish SDK Sources

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string
      sdk_repo_ref:
        description: |
          Branch or tag to checkout on the `expediagroup-sdk-core` repository.
          Leave empty to use the default branch.
        type: string
        default: ''

jobs:
  echo-things:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
  generate-and-publish-sources:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@mohnoor94/SDK-1441
    secrets: inherit
    with:
      name: rapid
      version: ${{ inputs.version }}
      transformations: "-th -te /v3 --operationIdsToTags"
      repository:  'ExpediaGroup/rapid-java-sdk'
      sdk_repo_ref: ${{ inputs.sdk_repo_ref }}