name: Run Examples
on:
  workflow_call:
    inputs:
      sdk_version:
        description: 'SDK version to run examples for'
        required: false
        type: string
        default: 'LATEST'
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
        default: '17'
      sdk_generation_worfklow_run_id:
        description: 'ID of the SDK generation workflow run'
        required: false
        type: string
        default: ''
    secrets:
      KEY:
        description: 'API Key'
        required: true
      SECRET:
        description: 'API Key'
        required: true

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/rapid-java-sdk'
          ref: 'OmarAlJarrah/add-cli-execution-plugin'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{github.event.inputs.jdk}}
          distribution: 'temurin'
      - name: Download SDK
        if: ${{ inputs.sdk_generation_worfklow_run_id != '' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ inputs.sdk_generation_worfklow_run_id }}
          name: sdk
          path: sdk
      - name: Install SDK
        if: ${{ inputs.sdk_generation_worfklow_run_id != '' }}
        working-directory: sdk
        run: ls -la && mvn clean install
      - name: Run Examples
        working-directory: examples
        run: mvn clean install exec:java -Drapid-java-sdk.sdk.version="${{inputs.sdk_version}}" -Dcom.expediagroup.rapidsdkjava.apikey="${{secrets.KEY}}" -Dcom.expediagroup.rapidsdkjava.apisecret="${{secrets.SECRET}}"
